config/routes.rb
Rails.application.routes.draw do
  root to: 'invoice_headers#index'
  resources :invoice_lines
  resources :invoice_headers
  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice_header.rb
class InvoiceHeader < ApplicationRecord
    has_many :invoice_line, dependent: :destroy
    validates :client_name, presence:true
    def subtotal
        self.invoice_line.map { |item| item.quantity * item.price }.sum
    end

    def discount_calculated
        subtotal * (self.rate / 100.0)
    end

    def totalRutine
        subtotal - discount_calculated 
    end
end

app/models/invoice_line.rb
class InvoiceLine < ApplicationRecord
    belongs_to :invoice_header
    validates :quantity, numericality: {greater_than_or_equal_to: 1}
    validates :price, numericality: {greater_than_or_equal_to: 0}
    validates :product_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoice_headers_controller.rb
class InvoiceHeadersController < ApplicationController
  before_action :set_invoice_header, only: [:show, :edit, :update, :destroy]

  # GET /invoice_headers
  # GET /invoice_headers.json
  def index
    puts DateTime.now()
    @invoice_headers = InvoiceHeader.all
  end

  # GET /invoice_headers/1
  # GET /invoice_headers/1.json
  def show
  end

  # GET /invoice_headers/new
  def new
    @invoice_header = InvoiceHeader.new
  end

  # GET /invoice_headers/1/edit
  def edit
  end

  # POST /invoice_headers
  # POST /invoice_headers.json
  def create
    
    puts invoice_header_params[:client_name]

    @invoice_header = InvoiceHeader.new(invoice_header_params)
    @invoice_header.creation_date = DateTime.now()
    @invoice_header.modification_date = DateTime.now()
    @invoice_header.total = @invoice_header.totalRutine

    respond_to do |format|
      if @invoice_header.save
        format.html { redirect_to @invoice_header, notice: 'Invoice header was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_header }
      else
        format.html { render :new }
        format.json { render json: @invoice_header.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_headers/1
  # PATCH/PUT /invoice_headers/1.json
  def update
    @invoice_header.modification_date = DateTime.now()
    @invoice_header.total = @invoice_header.totalRutine
    @invoice_header.save()
    
    respond_to do |format|
      if @invoice_header.update(invoice_header_params)
        format.html { redirect_to @invoice_header, notice: 'Invoice header was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_header }
      else
        format.html { render :edit }
        format.json { render json: @invoice_header.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_headers/1
  # DELETE /invoice_headers/1.json
  def destroy
    @invoice_header.destroy
    respond_to do |format|
      format.html { redirect_to invoice_headers_url, notice: 'Invoice header was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_header
      @invoice_header = InvoiceHeader.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_header_params
      params.require(:invoice_header).permit(:commit, :client_name, :client_last_name, :doc_id, :email, :phone, :rate, :address)
    end

end

app/controllers/invoice_lines_controller.rb
class InvoiceLinesController < ApplicationController
  before_action :set_invoice_line, only: [:show, :edit, :update, :destroy]

  # GET /invoice_lines
  # GET /invoice_lines.json
  def index
    @invoice_lines = InvoiceLine.all
  end

  # GET /invoice_lines/1
  # GET /invoice_lines/1.json
  def show
  end

  # GET /invoice_lines/new
  def new
    @invoice_line = InvoiceLine.new
  end

  # GET /invoice_lines/1/edit
  def edit
  end

  # POST /invoice_lines
  # POST /invoice_lines.json
  def create
    set_header
    tmp = invoice_line_params
    tmp[:invoice_header] = @invoice_header
    @invoice_line = InvoiceLine.new(tmp)
    @invoice_line.creation_date = DateTime.now()
    @invoice_line.modification_date = DateTime.now()
    @invoice_line.total = @invoice_line.quantity * @invoice_line.price

    @invoice_header.total = @invoice_header.totalRutine
    @invoice_header.save()

    respond_to do |format|
      if @invoice_line.save
        format.html { redirect_to @invoice_line, notice: 'Invoice line was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_line }
      else
        format.html { render :new }
        format.json { render json: @invoice_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_lines/1
  # PATCH/PUT /invoice_lines/1.json
  def update
    set_header

    @invoice_line.total = @invoice_line.quantity * @invoice_line.price
    @invoice_header.total = @invoice_header.totalRutine
    @invoice_header.save()

    respond_to do |format|
      if @invoice_line.update(invoice_line_params)
        format.html { redirect_to @invoice_line, notice: 'Invoice line was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_line }
      else
        format.html { render :edit }
        format.json { render json: @invoice_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_lines/1
  # DELETE /invoice_lines/1.json
  def destroy
    @invoice_line.destroy
    respond_to do |format|
      format.html { redirect_to invoice_lines_url, notice: 'Invoice line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_line
      @invoice_line = InvoiceLine.find(params[:id])
    end

    def set_header
      tmp = invoice_line_params
      puts tmp[:invoice_header_id].to_i
      @invoice_header = InvoiceHeader.find(tmp[:invoice_header_id].to_i)
    end

    # Only allow a list of trusted parameters through.
    def invoice_line_params
      params.require(:invoice_line).permit(:invoice_line, :description, :invoice_header, :invoice_header_id,:commit, :product_name, :quantity, :price, :invoice_header)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    def index

    end

    def show 
        @invoice = InvoiceHeader.find(params[:id])
        @items =@invoice.invoice_line

        respond_to do |format|
            format.html
            format.pdf do
                render pdf: "Invoice No. #{@invoice.id}",
                page_size: 'A4',
                layout: "pdf.html",
                template: "invoices/show.html.slim",
                orientation: "Portrait"
                # lowquality: false,
                # zoom: 1,
                # dpi: 75
            end
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoice_headers_helper.rb
module InvoiceHeadersHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/invoice_lines_helper.rb
module InvoiceLinesHelper
end

app/views/invoice_headers/_form.html.slim
= form_for(@invoice_header) do |f|
  - if @invoice_header.errors.any?
    div#error_explanation
      h2 = pluralize(@invoice_header.errors.count, "error") 
        prohibited this invoice header from being saved:
      ul
      - @invoice_header.errors.full_messages.each do |message|
        li = message 
  div.field
    label.label = f.label :client_name
    div.control
      = f.text_field :client_name, class: 'input'
  div.field
    label.label = f.label :client_last_name
    div.control
      = f.text_field :client_last_name, class: 'input'
  div.field
    label.label = f.label :doc_id
    div.control
      = f.text_field :doc_id, class: 'input'
  hr
  div.field
    label.label = f.label :email
    div.control
      = f.email_field :email, class: 'input'
  div.field
    label.label = f.label :phone
    div.control
      = f.text_field :phone, class: 'input'
  div.field
    label.label = f.label :address
    div.control
      = f.text_field :address, class: 'input'
  hr
  div.field
    label.label = f.label :rate
    div.control
      = f.number_field :rate, class: 'input', value: '0'
  = f.submit "Create", class: 'button is-primary'

app/views/invoice_headers/edit.html.slim
section.section
  div.container
    div.level
      div.level-left
        div.level-item
          div.title.is-size-5 Editing Invoice Header
      div.level-right
        div.level-item = link_to 'Back' ,invoice_headers_path , class: 'button is-link'
        div.level-item = link_to 'Show' ,@invoice_header , class: 'button is-primary'
    div.columns
      div.column.is-6.is-offset-3.box
        == render 'form'

app/views/invoice_headers/index.html.slim
p
  = notice
section.section
  div.container
    div.level
      div.level-left
        div.level-item
          div.title.is-size-4 Invoice Headers
      div.level-left
        div.level-item
          div.dropdown.is-hoverable.is-right
            div.dropdown-trigger
              div.button.is-dark  
                span.mx-2 = fa_icon "th-list"
                span Menu 
            div.dropdown-menu
              div.dropdown-content
                = link_to 'New Invoice Header', new_invoice_header_path, class: 'dropdown-item'
                = link_to 'Invoice Lines', invoice_lines_path, class: 'dropdown-item'

    table.table.is-stripped.is-fullwidth
      thead
        tr
          th Nr
          th Client
          / th Phone
          / th Email
          / th Address
          th C. Date
          th M. Date
          th Rate
          th Total
          th colspan=3
      tbody
        - @invoice_headers.each do |invoice_header|
          tr
            td = invoice_header.id
            td = invoice_header.client_name
            td = invoice_header.creation_date
            td = invoice_header.modification_date
            td = invoice_header.rate
            td = invoice_header.total
            td colspan=3
              div.dropdown.is-hoverable.is-right
                div.dropdown-trigger.has-cursor
                  span = fa_icon "list"
                div.dropdown-menu
                  div.dropdown-content
                    = link_to "Download PDF", invoice_path(invoice_header, format: :pdf), class: 'dropdown-item'
                    = link_to  "Show", invoice_header , class: 'dropdown-item'
                    = link_to  "Edit", edit_invoice_header_path(invoice_header), class: 'dropdown-item'
                    = link_to  "Destroy", invoice_header, method: :delete, data: { confirm: 'Are you sure?' } , class: 'dropdown-item'

app/views/invoice_headers/new.html.slim
section.section
  div.container
    div.level
      div.level-left
        div.level-item
          div.title.is-size-5 New Invoice Header 
      div.level-right
        div.level-item = link_to 'Back' ,invoice_headers_path , class: 'button is-link'
    div.columns
      div.column.is-6.is-offset-3.box
        == render 'form' 


    

app/views/invoice_headers/resume.html.slim
div pepe

app/views/invoice_headers/show.html.slim
p
  = notice

section.section
  div.container
    div.level
      div.level-left
        div.level-item
          div.title.is-size-5 Showing Invoice Header
      div.level-right
    div.columns
      div.column.is-6.is-offset-3
        div.card
            header.card-header
                p.card-header-title = @invoice_header.client_name
            div.card-content
                div.content
                    table
                        tbody
                            tr
                                td  Last name
                                td = @invoice_header.client_last_name
                            tr
                                td  Client DI
                                td = @invoice_header.doc_id
                            
                            tr
                                td  Phone
                                td = @invoice_header.phone
                            tr
                                td  Email
                                td = @invoice_header.email
                            tr
                                td  Address
                                td = @invoice_header.address
                            tr
                                td  Creation Date
                                td = @invoice_header.creation_date
                            tr
                                td  Modification Date
                                td = @invoice_header.modification_date
                            tr
                                td  Rate
                                td = @invoice_header.rate
                            tr
                                td  Total
                                td = @invoice_header.total
            footer.card-footer
                a.card-footer-item href=invoice_headers_path Back
                a.card-footer-item href=edit_invoice_header_path(@invoice_header) Edit

app/views/invoice_lines/_form.html.slim
= form_for(@invoice_line) do |f|
  - if @invoice_line.errors.any?
    div#error_explanation
      h2 = pluralize(@invoice_line.errors.count, "error") 
        prohibited this invoice header from being saved:
      ul
      - @invoice_line.errors.full_messages.each do |message|
        li = message 
  div.field
    label.label Header
    div.control
      = f.text_field :invoice_header_id, class: 'input'
  div.field
    label.label = f.label :product_name
    div.control
      = f.text_field :product_name, class: 'input'
  div.field
    label.label = f.label :quantity
    div.control
      = f.number_field :quantity, class: 'input', min: 1
  div.field
    label.label = f.label :price
    div.control
      = f.number_field :price, class: 'input'
  div.field
    label.label = f.label :description
    div.control
      = f.text_area :description, class: 'textarea'

  = f.submit "Create", class: 'button is-primary'

app/views/invoice_lines/edit.html.slim
section.section
  div.container
    div.level
      div.level-left
        div.level-item
          div.title.is-size-5 Editing Invoice Line
      div.level-right
        div.level-item = link_to 'Back' ,invoice_lines_path , class: 'button is-link'
        div.level-item = link_to 'Show' ,@invoice_line , class: 'button is-primary'
    div.columns
      div.column.is-6.is-offset-3.box
        == render 'form'

app/views/invoice_lines/index.html.slim
p
  = notice
section.section
  div.container
    div.level
      div.level-left
        div.level-item
          div.title.is-size-4 Invoice Lines
      div.level-left
        div.level-item
          div.dropdown.is-hoverable.is-right
            div.dropdown-trigger
              div.button.is-dark  
                span.mx-2 = fa_icon "th-list"
                span Menu 
            div.dropdown-menu
              div.dropdown-content
                = link_to 'Home', invoice_headers_path, class: 'dropdown-item'
                = link_to 'New Invoice Line', new_invoice_line_path, class: 'dropdown-item'

    table.table.is-stripped.is-fullwidth
      thead
        tr
          th Prod. Name
          th Inv. Header
          th C. Date
          th M. Date
          th.has-text-right Quantity
          th.has-text-right Price
          th.has-text-right Total
          th colspan=3
      tbody
        - @invoice_lines.each do |invoice_lines|
          tr
            td = invoice_lines.product_name
            td = invoice_lines.invoice_header_id.to_s
            td = invoice_lines.creation_date
            td = invoice_lines.modification_date
            td.has-text-right = invoice_lines.quantity
            td.has-text-right = invoice_lines.price
            td.has-text-right = invoice_lines.total
            td 
              div.dropdown.is-hoverable.is-right
                div.dropdown-trigger.has-cursor
                  span = fa_icon "list"
                div.dropdown-menu
                  div.dropdown-content
                    = link_to  "Show", invoice_lines , class: 'dropdown-item'
                    = link_to  "Edit", edit_invoice_line_path(invoice_lines), class: 'dropdown-item'
                    = link_to  "Destroy", invoice_lines, method: :delete, data: { confirm: 'Are you sure?' } , class: 'dropdown-item'

app/views/invoice_lines/new.html.slim
section.section
  div.container
    div.level
      div.level-left
        div.level-item
          div.title.is-size-5 New Invoice Line 
      div.level-right
        div.level-item = link_to 'Back' ,invoice_lines_path , class: 'button is-link'
    div.columns
      div.column.is-6.is-offset-3.box
        == render 'form' 


    

app/views/invoice_lines/show.html.slim
p
  = notice

section.section
  div.container
    div.level
      div.level-left
        div.level-item
          div.title.is-size-5 Showing Invoice Line
      div.level-right
    div.columns
      div.column.is-6.is-offset-3
        div.card
            header.card-header
                p.card-header-title = @invoice_line.product_name
            div.card-content
                div.content
                    table
                        tbody
                            tr
                                td  Creation Date
                                td = @invoice_line.creation_date
                            tr
                                td  Modification Date
                                td = @invoice_line.modification_date
                            tr
                                td  quantity
                                td = @invoice_line.quantity
                            tr
                                td  Price
                                td = @invoice_line.price
                            tr
                                td  Total
                                td = @invoice_line.total
                            tr
                                td colspan="2" = @invoice_line.description
            footer.card-footer
                a.card-footer-item href=invoice_lines_path Back
                a.card-footer-item href=edit_invoice_line_path(@invoice_line) Edit

app/views/invoices/index.html.slim
pepepe

app/views/invoices/show.html.slim
div.columns
    div.column.is-narrow
        = wicked_pdf_image_tag "logo.png",:width => "90", :height=>"85"
    div.column.is-narrow
        p.title.is-3 Invoice resume
        p.subtitle.is-4
            span Client 
            span.px-2 = @invoice.client_name 
            span.px-2 = @invoice.client_last_name
            span.px-2 = @invoice.doc_id  

hr

p.title.is-5 Contact
p.my-0 = @invoice.phone
p.my-0 = @invoice.email
p.my-0 = @invoice.address

p.title.is-6 Products

table.table-ext
    thead
        tr
            th.has-text-left Product name
            th.has-text-left C.Date
            th.has-text-left M.Date
            th.has-text-right Quantity
            th.has-text-right Price
            th.has-text-right Subtotal

    tbody
        -@items.each do |item|
            tr
                td = item.product_name
                td = item.creation_date
                td = item.modification_date
                td.has-text-right = item.quantity
                td.has-text-right = item.price
                td.has-text-right = item.total
    tfoot
        tr
            td colspan="3"
                span.px-2 Rate
                span = @invoice.rate
            td colspan="3"
                span.px-2 Total
                span = @invoice.total


span Total = @invoice.total

app/views/layouts/application.html.slim
doctype 5
html.screen-ext
  head
    title = yield(:title)
    meta name="viewport" content="width=device-width, initial-scale=1.0 , maximum-scale=1.0, user-scalable=no"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  
  body.body-ext.screen-ext
      = yield

app/views/layouts/pdf.html.slim
doctype 5
html
  head
    title = yield(:title)
    meta name="viewport" content="width=device-width, initial-scale=1.0 , maximum-scale=1.0, user-scalable=no"
    = stylesheet_link_tag wicked_pdf_asset_base64 ("application")
    = wicked_pdf_stylesheet_link_tag "application"
    = csrf_meta_tags
  
  body

    == yield 